In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import rc
rc('font', family='Malgun Gothic')
rc('axes', unicode_minus=False)

In [2]:
import datetime
import os
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import requests
import json

In [3]:
date_today = datetime.date.today()
date_key = date_today.strftime('%y%m%d')

#### 종목 코드 save by market

In [4]:
market_code = 'stockMkt'
# 'kospi': 'stockMkt',
# 'kosdaq': 'kosdaqMkt',
# 'konex': 'konexMkt'

In [5]:
sto_code_url = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=' + market_code

In [6]:
sto_code_df = pd.read_html(sto_code_url)[0]
sto_code_df[:5]

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,JS전선,5560,절연선 및 케이블 제조업,"선박선,고무선,전력선,통신선 제조",2007-11-12,12월,이익희,http://www.jscable.co.kr,충청남도
1,거북선2호,101380,NaN,운송장비(선박) 임대,2008-04-25,12월,신주선,NaN,부산광역시
2,거북선6호,114140,NaN,NaN,2009-10-01,12월,김연신,NaN,제주특별자치도
3,교보메리츠,64900,NaN,"부동산 투자,운용",2002-01-30,12월,김 상 진,NaN,서울특별시
4,국제관광공사,28780,NaN,NaN,1966-03-18,12월,NaN,NaN,NaN

In [7]:
save_n_code_df = ('data/code_list/' + 'code_list_' + market_code + '_' + date_key + '.csv').strip()
save_n_code_df

'data/code_list/code_list_stockMkt_190801.csv'

In [8]:
sto_code_df.to_csv(save_n_code_df, encoding='euc-kr', index=False) #cp949
print('save >> ' + save_n_code_df)

save >> data/code_list/code_list_stockMkt_190801.csv

#### 종목코드 load

In [9]:
os.listdir('data/code_list')

['code_list_190728.csv',
 'code_list_190729.csv',
 'code_list_190730.csv',
 'code_list_stockMkt_190730.csv',
 'code_list_stockMkt_190801.csv']

In [10]:
select_file_code_df = ('data/code_list/' + os.listdir('data/code_list')[-1])
select_file_code_df

'data/code_list/code_list_stockMkt_190801.csv'

In [11]:
sto_code_df = pd.read_csv(select_file_code_df, encoding='euc-kr')
sto_code_df[:3]

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,JS전선,5560,절연선 및 케이블 제조업,"선박선,고무선,전력선,통신선 제조",2007-11-12,12월,이익희,http://www.jscable.co.kr,충청남도
1,거북선2호,101380,NaN,운송장비(선박) 임대,2008-04-25,12월,신주선,NaN,부산광역시
2,거북선6호,114140,NaN,NaN,2009-10-01,12월,김연신,NaN,제주특별자치도

In [12]:
sto_code_df['종목코드'] = sto_code_df['종목코드'].map('{:06d}'.format)

In [13]:
sto_code_sort = sto_code_df[['회사명', '종목코드']]
sto_code_sort[-5:]

          회사명    종목코드
3730  지앤이헬스케어  299480
3731       툴젠  199800
3732       틸론  217880
3733    판도라티비  202960
3734    한국비엔씨  226610

In [14]:
sto_code_sort.shape

(3735, 2)

#### sise

In [208]:
def url_creater(what) :
    target_url = []
    target_code = []
#   target = ['국내', '해외', '환율', 'WTI', '휘발유', '국제금', '국내금']
    url_base = 'https://finance.naver.com/'
    url_ref = {'국내' : 'sise/sise_index_day.nhn?code=', 
              '해외' : 'world/worldDayListJson.nhn?symbol=', 
              '환율' : 'marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_', 
              'WTI' : 'marketindex/worldDailyQuote.nhn?marketindexCd=', 
              '휘발유' : 'marketindex/oilDailyQuote.nhn?marketindexCd=', 
              '국제금' : 'marketindex/worldDailyQuote.nhn?marketindexCd=', 
              '국내금' : 'marketindex/goldDailyQuote.nhn?'}
    cate_code = {'국내' : ['KOSPI', 'KOSDAQ', 'KPI200'], 
              '해외' : ['DJI@DJI', 'NII@NI225', 'LNS@FTSE100', 
                      'NAS@IXIC', 'SHS@000001', 'PAS@CAC40', 
                      'SPI@SPX', 'HSI@HSI', 'XTR@DAX30' ], 
              '환율' : ['USDKRW', 'JPYKRW', 'EURKRW', 'CNYKRW'], 
              'WTI' : ['OIL_CL'], 
              '휘발유' : ['OIL_GSL'], 
              '국제금' : ['CMDT_GC'], 
              '국내금' : ['']}
    pager = {'국내' : '&page=', 
              '해외' : '&fdtc=0&page=', 
              '환율' : '&page=', 
              'WTI' : '&fdtc=2&page=', 
              '휘발유' : '&page=', 
              '국제금' : '&fdtc=2&page=', 
              '국내금' : '&page='}
    for i in range(len(cate_code[what])) :
        target_url += [url_base + url_ref[what] + cate_code[what][i] + pager[what]]
        target_code += [cate_code[what][i]]
    return target_url, target_code

In [218]:
url_creater('국내')[1][2]

'KPI200'

In [210]:
def last_page_finder(url):
    target_html = BeautifulSoup(urlopen(url).read(), 'lxml') #html.parser
    page_pkg = target_html.find_all("table") #,align="center"
    if page_pkg ==[] : return 500
    else :
        last_page_pkg = page_pkg[0].find_all("td",class_="pgRR")
        if last_page_pkg ==[] : 
            last_page_pkg = page_pkg[1].find_all("td",class_="pgRR")
        last_page_pkg = last_page_pkg[0].a.get('href')
        last_page_num = int(last_page_pkg.split("=")[-1].strip())
        return last_page_num

In [232]:
def info_collector_html(market) :
    info_df = pd.DataFrame()
    target_url = url_creater(market)
    k = -1
#     last_page_num = last_page_finder(target_url+'1')
    for i in target_url[0] :
        temp_df = pd.DataFrame()
        k += 1
        last_page_num = last_page_finder(i+'1')
        for j in range(1, last_page_num+1) :
            page_url = (f'{i}{j}')
            temp_df = temp_df.append(pd.read_html(page_url, header=0)[0], 
                                     ignore_index=True)
            temp_df = temp_df.dropna(axis=0)

        temp_df.set_index('날짜', inplace=True)
        temp_df.columns = (temp_df.columns + '_' + target_url[1][k])
        info_df = pd.concat([info_df, temp_df], axis=1, sort=False)
    return info_df

In [224]:
k = 0
for i in range(5):
    print(i)
    k += 1
    print(k)
    print()

0
1

1
2

2
3

3
4

4
5

In [125]:
# def info_collector_html(base_url, code) :
#     info_df = pd.DataFrame()
#     target_url = base_url + code
#     last_page_num = last_page_finder(target_url)
#     for i in range(1, last_page_num+1) :
#         page_url = (f'{target_url}&page={i}')
#         info_df = info_df.append(pd.read_html(page_url, header=0)[0], ignore_index=True)
#         info_df = info_df.dropna(axis=0)
#     return info_df

In [196]:
# 해외지수 전용 (no table)
def info_collector_ajax(base_url, code) :
    info_df = pd.DataFrame()
    target_url = base_url + code
    last_page_num = last_page_finder(target_url)
    cols = {"xymd":"날짜","clos":'종가',"diff":'전일비',
            "open":'시가',"high":'고가',"low":'저가',
            "rate":"rate","gvol":"gvol", "symb":"symb"}
    for i in range(1, last_page_num+1) :
        page_url = (f'{target_url}&fdtc=0&page={i}')
        info_df = info_df.append(pd.DataFrame(requests.get(page_url).json()), ignore_index=True)
        info_df = info_df.dropna(axis=0)
        info_df = info_df.drop_duplicates(['xymd'])
    info_df.rename(columns=cols, inplace=True)
    return info_df

[지수]

* 국내

In [17]:
base_url_jisu_do = 'https://finance.naver.com/sise/sise_index_day.nhn?code='

In [18]:
code_jisu_do = ['KOSPI', 'KOSDAQ', 'KPI200']

In [67]:
jisu_do_info_df = pd.DataFrame()
for i in code_jisu_do :
    temp = info_collector_html(base_url_jisu_do, i)
    temp.set_index('날짜', inplace=True)
    temp.columns = (temp.columns + '_' + i)
    jisu_do_info_df = pd.concat([jisu_do_info_df, temp], axis=1, sort=False)
jisu_do_info_df

,체결가_KOSPI,전일비_KOSPI,등락률_KOSPI,거래량(천주)_KOSPI,거래대금(백만)_KOSPI,체결가_KOSDAQ,전일비_KOSDAQ,등락률_KOSDAQ,거래량(천주)_KOSDAQ,거래대금(백만)_KOSDAQ,체결가_KPI200,전일비_KPI200,등락률_KPI200,거래량(천주)_KPI200,거래대금(백만)_KPI200
2019.08.01,2017.30,7.25,-0.36%,415701.0,3870951.0,622.47,7.71,-1.22%,630719.0,3786046.0,266.04,0.30,-0.11%,64143.0,2537888.0
2019.07.31,2024.55,14.13,-0.69%,578033.0,5415666.0,630.18,4.54,+0.73%,755260.0,4160117.0,266.34,2.61,-0.97%,91703.0,3731560.0
2019.07.30,2038.68,9.20,+0.45%,538759.0,3821938.0,625.64,6.86,+1.11%,704143.0,3462591.0,268.95,1.20,+0.45%,63169.0,2334005.0
2019.07.29,2029.48,36.78,-1.78%,596166.0,4626034.0,618.78,25.81,-4.00%,771304.0,3712485.0,267.75,4.50,-1.65%,77793.0,2804706.0
2019.07.26,2066.26,8.22,-0.40%,583332.0,5056450.0,644.59,7.81,-1.20%,870552.0,3896380.0,272.25,0.79,-0.29%,88517.0,3404986.0
2019.07.25,2074.48,7.82,-0.38%,590890.0,5126430.0,652.40,7.43,-1.13%,856206.0,4105781.0,273.04,0.18,-0.07%,94460.0,3835185.0
2019.07.24,2082.30,19.15,-0.91%,841580.0,4115461.0,659.83,8.82,-1.32%,955261.0,4915984.0,273.22,2.70,-0.98%,82752.0,2919409.0
2019.07.23,2101.45,8.11,+0.39%,640162.0,4523644.0,668.65,6.13,-0.91%,884196.0,4534091.0,275.92,1.37,+0.50%,93952.0,3219043.0
2019.07.22,2093.34,1.02,-0.05%,320412.0,3156360.0,674.78,0.72,+0.11%,634148.0,3312898.0,274.55,0.00,0.00%,59881.0,2340357.0
2019.07.19,2094.36,27.81,+1.35%,386118.0,4037112.0,674.06,8.91,+1.34%,743055.0,3886505.0,274.55,3.88,+1.43%,85702.0,2956076.0
2019.07.18,2066.55,6.37,-0.31%,437178.0,3848957.0,665.15,1.13,-0.17%,824342.0,4207088.0,270.67,0.81,-0.30%,78649.0,2607494.0
2019.07.17,2072.92,18.95,-0.91%,752119.0,4549215.0,666.28,8.14,-1.21%,887319.0,4149075.0,271.48,2.57,-0.94%,115622.0,3031700.0
2019.07.16,2091.87,9.39,+0.45%,674500.0,5158374.0,674.42,0.37,-0.05%,811124.0,4528508.0,274.05,1.41,+0.52%,134388.0,3589437.0
2019.07.15,2082.48,4.18,-0.20%,455075.0,3656611.0,674.79,6.38,-0.94%,705069.0,4146102.0,272.64,0.04,-0.01%,82080.0,2560620.0
2019.07.12,2086.66,6.08,+0.29%,398353.0,3714594.0,681.17,4.08,+0.60%,725252.0,4079424.0,272.68,0.90,+0.33%,54810.0,2446249.0
2019.07.11,2080.58,21.80,+1.06%,368242.0,4934006.0,677.09,10.19,+1.53%,775167.0,4077292.0,271.78,3.03,+1.13%,104926.0,3844891.0
2019.07.10,2058.78,6.75,+0.33%,350018.0,3867014.0,666.90,9.10,+1.38%,761788.0,3791055.0,268.75,1.03,+0.38%,66266.0,2805302.0
2019.07.09,2052.03,12.14,-0.59%,433474.0,4361543.0,657.80,10.92,-1.63%,866024.0,4057741.0,267.72,0.83,-0.31%,70609.0,3029601.0
2019.07.08,2064.17,46.42,-2.20%,507760.0,4275766.0,668.72,25.45,-3.67%,754947.0,4192796.0,268.55,5.80,-2.11%,74076.0,2754746.0
2019.07.05,2110.59,1.86,+0.09%,452463.0,3959700.0,694.17,2.90,+0.42%,720411.0,3998049.0,274.35,0.19,-0.07%,59562.0,2631490.0
2019.07.04,2108.73,12.71,+0.61%,440234.0,4471126.0,691.27,1.77,-0.26%,752767.0,4076625.0,274.54,2.17,+0.80%,76980.0,2842808.0
2019.07.03,2096.02,26.00,-1.23%,510185.0,4512416.0,693.04,3.21,-0.46%,662714.0,3919284.0,272.37,3.60,-1.30%,96506.0,3104200.0
2019.07.02,2122.02,7.72,-0.36%,442102.0,4031531.0,696.25,0.25,+0.04%,685752.0,3998609.0,275.97,1.30,-0.47%,64740.0,2670191.0
2019.07.01,2129.74,0.88,-0.04%,405153.0,4544544.0,696.00,5.47,+0.79%,724412.0,5096420.0,277.27,0.23,-0.08%,73429.0,3276750.0
2019.06.28,2130.62,3.70,-0.17%,529503.0,4191165.0,690.53,7.68,-1.10%,766069.0,4102087.0,277.50,0.25,-0.09%,66426.0,2827388.0
2019.06.27,2134.32,12.47,+0.59%,637264.0,5064017.0,698.21,11.16,-1.57%,894894.0,5066792.0,277.75,2.22,+0.81%,65816.0,3330708.0
2019.06.26,2121.85,0.21,+0.01%,725559.0,4389757.0,709.37,0.65,-0.09%,969271.0,4672753.0,275.53,0.25,+0.09%,58246.0,2605449.0
2019.06.25,2121.64,4.69,-0.22%,634514.0,4198154.0,710.02,7.67,-1.07%,1045305.0,4822920.0,275.28,0.30,-0.11%,59809.0,2609117.0
2019.06.24,2126.33,0.71,+0.03%,660547.0,3996337.0,717.69,4.95,-0.68%,907855.0,3647703.0,275.58,0.10,+0.04%,55183.0,2206332.0
2019.06.21,2125.62,5.67,-0.27%,680199.0,5112321.0,722.64,4.68,-0.64%,1085095.0,4315751.0,275.48,0.53,-0.19%,75383.0,3193828.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990.02.08,882.52,2.13,+0.24%,12408.0,262339.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.07,880.39,6.47,-0.73%,11570.0,250378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.06,886.86,9.41,+1.07%,11466.0,241199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.05,877.45,2.53,+0.29%,7954.0,159875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.03,874.92,3.23,-0.37%,6349.0,126534.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.02,878.15,7.68,-0.87%,11021.0,217685.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.01,885.83,10.33,-1.15%,12308.0,241765.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.31,896.16,7.69,+0.87%,18172.0,374622.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.30,888.47,8.85,-0.99%,15218.0,329413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.29,897.32,8.43,-0.93%,12267.0,268079.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.25,905.75,2.17,+0.24%,23607.0,523123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.24,903.58,13.06,+1.47%,20476.0,448096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.23,890.52,8.37,-0.93%,17487.0,383059.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.22,898.89,25.92,+2.97%,17409.0,362616.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.20,872.97,4.77,+0.55%,6356.0,129936.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.19,868.20,6.61,-0.76%,7786.0,158320.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.18,874.81,0.40,+0.05%,9066.0,182555.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.17,874.41,9.02,-1.02%,6927.0,141562.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.16,883.43,0.39,+0.04%,10384.0,216377.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.15,883.04,10.43,-1.17%,8854.0,184112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.13,893.47,9.64,-1.07%,7384.0,156742.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.12,903.11,0.16,-0.02%,11627.0,250693.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.11,903.27,8.21,-0.90%,12647.0,274573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.10,911.48,8.73,-0.95%,15278.0,322830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.09,920.21,0.75,+0.08%,18646.0,382992.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.08,919.46,6.60,+0.72%,17577.0,369946.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.06,912.86,2.25,-0.25%,12519.0,269397.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.05,915.11,13.71,-1.48%,22179.0,476295.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.04,928.82,20.23,+2.23%,18094.0,405061.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003.09.09,NaN,NaN,NaN,NaN,NaN,491.90,0.36,+0.74%,373589.0,912569.0,NaN,NaN,NaN,NaN,NaN

In [68]:
jisu_do_info_df.shape

(7722, 15)

In [69]:
jisu_do_info_df.isnull().sum()

체결가_KOSPI             1
전일비_KOSPI             1
등락률_KOSPI             1
거래량(천주)_KOSPI         1
거래대금(백만)_KOSPI        1
체결가_KOSDAQ         1916
전일비_KOSDAQ         1916
등락률_KOSDAQ         1916
거래량(천주)_KOSDAQ     1916
거래대금(백만)_KOSDAQ    1916
체결가_KPI200         4364
전일비_KPI200         4364
등락률_KPI200         4364
거래량(천주)_KPI200     4364
거래대금(백만)_KPI200    4364
dtype: int64

In [234]:
dome_info = info_collector_html('국내')
dome_info

,체결가_KOSPI,전일비_KOSPI,등락률_KOSPI,거래량(천주)_KOSPI,거래대금(백만)_KOSPI,체결가_KOSDAQ,전일비_KOSDAQ,등락률_KOSDAQ,거래량(천주)_KOSDAQ,거래대금(백만)_KOSDAQ,체결가_KPI200,전일비_KPI200,등락률_KPI200,거래량(천주)_KPI200,거래대금(백만)_KPI200
2019.08.01,2017.34,7.21,-0.36%,461743.0,4443149.0,622.26,7.92,-1.26%,694237.0,4161131.0,265.73,0.61,-0.23%,72578.0,2900144.0
2019.07.31,2024.55,14.13,-0.69%,578033.0,5415666.0,630.18,4.54,+0.73%,755260.0,4160117.0,266.34,2.61,-0.97%,91703.0,3731560.0
2019.07.30,2038.68,9.20,+0.45%,538759.0,3821938.0,625.64,6.86,+1.11%,704143.0,3462591.0,268.95,1.20,+0.45%,63169.0,2334005.0
2019.07.29,2029.48,36.78,-1.78%,596166.0,4626034.0,618.78,25.81,-4.00%,771304.0,3712485.0,267.75,4.50,-1.65%,77793.0,2804706.0
2019.07.26,2066.26,8.22,-0.40%,583332.0,5056450.0,644.59,7.81,-1.20%,870552.0,3896380.0,272.25,0.79,-0.29%,88517.0,3404986.0
2019.07.25,2074.48,7.82,-0.38%,590890.0,5126430.0,652.40,7.43,-1.13%,856206.0,4105781.0,273.04,0.18,-0.07%,94460.0,3835185.0
2019.07.24,2082.30,19.15,-0.91%,841580.0,4115461.0,659.83,8.82,-1.32%,955261.0,4915984.0,273.22,2.70,-0.98%,82752.0,2919409.0
2019.07.23,2101.45,8.11,+0.39%,640162.0,4523644.0,668.65,6.13,-0.91%,884196.0,4534091.0,275.92,1.37,+0.50%,93952.0,3219043.0
2019.07.22,2093.34,1.02,-0.05%,320412.0,3156360.0,674.78,0.72,+0.11%,634148.0,3312898.0,274.55,0.00,0.00%,59881.0,2340357.0
2019.07.19,2094.36,27.81,+1.35%,386118.0,4037112.0,674.06,8.91,+1.34%,743055.0,3886505.0,274.55,3.88,+1.43%,85702.0,2956076.0
2019.07.18,2066.55,6.37,-0.31%,437178.0,3848957.0,665.15,1.13,-0.17%,824342.0,4207088.0,270.67,0.81,-0.30%,78649.0,2607494.0
2019.07.17,2072.92,18.95,-0.91%,752119.0,4549215.0,666.28,8.14,-1.21%,887319.0,4149075.0,271.48,2.57,-0.94%,115622.0,3031700.0
2019.07.16,2091.87,9.39,+0.45%,674500.0,5158374.0,674.42,0.37,-0.05%,811124.0,4528508.0,274.05,1.41,+0.52%,134388.0,3589437.0
2019.07.15,2082.48,4.18,-0.20%,455075.0,3656611.0,674.79,6.38,-0.94%,705069.0,4146102.0,272.64,0.04,-0.01%,82080.0,2560620.0
2019.07.12,2086.66,6.08,+0.29%,398353.0,3714594.0,681.17,4.08,+0.60%,725252.0,4079424.0,272.68,0.90,+0.33%,54810.0,2446249.0
2019.07.11,2080.58,21.80,+1.06%,368242.0,4934006.0,677.09,10.19,+1.53%,775167.0,4077292.0,271.78,3.03,+1.13%,104926.0,3844891.0
2019.07.10,2058.78,6.75,+0.33%,350018.0,3867014.0,666.90,9.10,+1.38%,761788.0,3791055.0,268.75,1.03,+0.38%,66266.0,2805302.0
2019.07.09,2052.03,12.14,-0.59%,433474.0,4361543.0,657.80,10.92,-1.63%,866024.0,4057741.0,267.72,0.83,-0.31%,70609.0,3029601.0
2019.07.08,2064.17,46.42,-2.20%,507760.0,4275766.0,668.72,25.45,-3.67%,754947.0,4192796.0,268.55,5.80,-2.11%,74076.0,2754746.0
2019.07.05,2110.59,1.86,+0.09%,452463.0,3959700.0,694.17,2.90,+0.42%,720411.0,3998049.0,274.35,0.19,-0.07%,59562.0,2631490.0
2019.07.04,2108.73,12.71,+0.61%,440234.0,4471126.0,691.27,1.77,-0.26%,752767.0,4076625.0,274.54,2.17,+0.80%,76980.0,2842808.0
2019.07.03,2096.02,26.00,-1.23%,510185.0,4512416.0,693.04,3.21,-0.46%,662714.0,3919284.0,272.37,3.60,-1.30%,96506.0,3104200.0
2019.07.02,2122.02,7.72,-0.36%,442102.0,4031531.0,696.25,0.25,+0.04%,685752.0,3998609.0,275.97,1.30,-0.47%,64740.0,2670191.0
2019.07.01,2129.74,0.88,-0.04%,405153.0,4544544.0,696.00,5.47,+0.79%,724412.0,5096420.0,277.27,0.23,-0.08%,73429.0,3276750.0
2019.06.28,2130.62,3.70,-0.17%,529503.0,4191165.0,690.53,7.68,-1.10%,766069.0,4102087.0,277.50,0.25,-0.09%,66426.0,2827388.0
2019.06.27,2134.32,12.47,+0.59%,637264.0,5064017.0,698.21,11.16,-1.57%,894894.0,5066792.0,277.75,2.22,+0.81%,65816.0,3330708.0
2019.06.26,2121.85,0.21,+0.01%,725559.0,4389757.0,709.37,0.65,-0.09%,969271.0,4672753.0,275.53,0.25,+0.09%,58246.0,2605449.0
2019.06.25,2121.64,4.69,-0.22%,634514.0,4198154.0,710.02,7.67,-1.07%,1045305.0,4822920.0,275.28,0.30,-0.11%,59809.0,2609117.0
2019.06.24,2126.33,0.71,+0.03%,660547.0,3996337.0,717.69,4.95,-0.68%,907855.0,3647703.0,275.58,0.10,+0.04%,55183.0,2206332.0
2019.06.21,2125.62,5.67,-0.27%,680199.0,5112321.0,722.64,4.68,-0.64%,1085095.0,4315751.0,275.48,0.53,-0.19%,75383.0,3193828.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990.02.08,882.52,2.13,+0.24%,12408.0,262339.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.07,880.39,6.47,-0.73%,11570.0,250378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.06,886.86,9.41,+1.07%,11466.0,241199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.05,877.45,2.53,+0.29%,7954.0,159875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.03,874.92,3.23,-0.37%,6349.0,126534.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.02,878.15,7.68,-0.87%,11021.0,217685.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.02.01,885.83,10.33,-1.15%,12308.0,241765.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.31,896.16,7.69,+0.87%,18172.0,374622.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.30,888.47,8.85,-0.99%,15218.0,329413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.29,897.32,8.43,-0.93%,12267.0,268079.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.25,905.75,2.17,+0.24%,23607.0,523123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.24,903.58,13.06,+1.47%,20476.0,448096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.23,890.52,8.37,-0.93%,17487.0,383059.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.22,898.89,25.92,+2.97%,17409.0,362616.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.20,872.97,4.77,+0.55%,6356.0,129936.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.19,868.20,6.61,-0.76%,7786.0,158320.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.18,874.81,0.40,+0.05%,9066.0,182555.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.17,874.41,9.02,-1.02%,6927.0,141562.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.16,883.43,0.39,+0.04%,10384.0,216377.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.15,883.04,10.43,-1.17%,8854.0,184112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.13,893.47,9.64,-1.07%,7384.0,156742.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.12,903.11,0.16,-0.02%,11627.0,250693.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.11,903.27,8.21,-0.90%,12647.0,274573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.10,911.48,8.73,-0.95%,15278.0,322830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.09,920.21,0.75,+0.08%,18646.0,382992.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.08,919.46,6.60,+0.72%,17577.0,369946.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.06,912.86,2.25,-0.25%,12519.0,269397.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.05,915.11,13.71,-1.48%,22179.0,476295.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990.01.04,928.82,20.23,+2.23%,18094.0,405061.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003.09.09,NaN,NaN,NaN,NaN,NaN,491.90,0.36,+0.74%,373589.0,912569.0,NaN,NaN,NaN,NaN,NaN

In [235]:
dome_info.shape

(7722, 15)

In [236]:
dome_info.isnull().sum()

체결가_KOSPI             1
전일비_KOSPI             1
등락률_KOSPI             1
거래량(천주)_KOSPI         1
거래대금(백만)_KOSPI        1
체결가_KOSDAQ         1916
전일비_KOSDAQ         1916
등락률_KOSDAQ         1916
거래량(천주)_KOSDAQ     1916
거래대금(백만)_KOSDAQ    1916
체결가_KPI200         4364
전일비_KPI200         4364
등락률_KPI200         4364
거래량(천주)_KPI200     4364
거래대금(백만)_KPI200    4364
dtype: int64

- 해외

In [22]:
base_url_jisu_exp = 'https://finance.naver.com/world/worldDayListJson.nhn?symbol='

In [23]:
code_jisu_exp = ['DJI@DJI', 'NII@NI225', 'LNS@FTSE100', 'NAS@IXIC', 'SHS@000001',
                'PAS@CAC40', 'SPI@SPX', 'HSI@HSI', 'XTR@DAX30' ]

In [24]:
# 다우산업 : DJI@DJI    ,    # 니케이225 : NII@NI225
# 영국 : LNS@FTSE100    ,    # 나스닥종합 : NAS@IXIC
# 상해종합 : SHS@000001 ,    # 프랑스 : PAS@CAC40
# S&P 500 : SPI@SPX     ,    # 항셍 : HSI@HSI
# 독일 : XTR@DAX30

In [38]:
jisu_exp_info_df = pd.DataFrame()
for i in code_jisu_exp :
    temp = info_collector_ajax(base_url_jisu_exp, i)
    temp.set_index('날짜', inplace=True)
    temp.columns = (temp.columns + '_' + i)
    jisu_exp_info_df = pd.concat([jisu_exp_info_df, temp], axis=1, sort=False)
jisu_exp_info_df

,종가_DJI@DJI,전일비_DJI@DJI,gvol_DJI@DJI,고가_DJI@DJI,저가_DJI@DJI,시가_DJI@DJI,rate_DJI@DJI,symb_DJI@DJI,종가_NII@NI225,전일비_NII@NI225,...,rate_HSI@HSI,symb_HSI@HSI,종가_XTR@DAX30,전일비_XTR@DAX30,gvol_XTR@DAX30,고가_XTR@DAX30,저가_XTR@DAX30,시가_XTR@DAX30,rate_XTR@DAX30,symb_XTR@DAX30
20190731,26864.27,-333.75,388998694.0,27281.65,26719.60,27244.67,-1.23,DJI@DJI,21521.53,-187.78,...,-1.31,HSI@HSI,12189.04,41.80,94019580.0,12226.49,12139.03,12149.09,0.34,XTR@DAX30
20190730,27198.02,-23.33,293245226.0,27224.36,27069.86,27145.39,-0.09,DJI@DJI,21709.31,92.51,...,0.14,HSI@HSI,12147.24,-270.23,118257935.0,12404.51,12115.28,12398.24,-2.18,XTR@DAX30
20190729,27221.35,28.90,259316069.0,27275.85,27178.06,27192.24,0.11,DJI@DJI,21616.80,-41.35,...,-1.03,HSI@HSI,12417.47,-2.43,66298553.0,12473.97,12387.58,12398.29,-0.02,XTR@DAX30
20190726,27192.45,51.47,243198930.0,27213.70,27123.25,27166.00,0.19,DJI@DJI,21658.15,-98.40,...,-0.69,HSI@HSI,12419.90,57.80,73308041.0,12428.05,12356.15,12363.86,0.47,XTR@DAX30
20190725,27140.98,-128.99,244021675.0,27298.43,27062.48,27247.39,-0.47,DJI@DJI,21756.55,46.98,...,0.25,HSI@HSI,12362.10,-160.79,119522742.0,12599.93,12299.10,12576.02,-1.28,XTR@DAX30
20190724,27269.97,-79.22,245881077.0,27291.04,27191.12,27262.24,-0.29,DJI@DJI,21709.57,88.69,...,0.20,HSI@HSI,12522.89,32.15,96088881.0,12550.34,12476.55,12510.52,0.26,XTR@DAX30
20190723,27349.19,177.29,250797407.0,27368.81,27204.58,27231.86,0.65,DJI@DJI,21620.88,204.09,...,0.34,HSI@HSI,12490.74,201.34,97321761.0,12531.16,12369.19,12384.66,1.64,XTR@DAX30
20190722,27171.90,17.70,226949931.0,27227.77,27088.90,27174.18,0.07,DJI@DJI,21416.79,-50.20,...,-1.37,HSI@HSI,12289.40,29.33,60318198.0,12346.02,12236.70,12243.58,0.24,XTR@DAX30
20190719,27154.20,-68.77,287691866.0,27342.96,27145.78,27246.38,-0.25,DJI@DJI,21466.99,420.75,...,1.07,HSI@HSI,12260.07,32.22,80209539.0,12340.11,12211.67,12302.64,0.26,XTR@DAX30
20190718,27222.97,3.12,218821655.0,27266.81,27068.79,27191.98,0.01,DJI@DJI,21046.24,-422.94,...,-0.46,HSI@HSI,12227.85,-113.18,75541798.0,12296.30,12172.59,12194.33,-0.92,XTR@DAX30
20190717,27219.85,-115.78,196775910.0,27343.06,27218.38,27320.91,-0.42,DJI@DJI,21469.18,-66.07,...,-0.09,HSI@HSI,12341.03,-89.94,75111139.0,12453.33,12324.33,12429.87,-0.72,XTR@DAX30
20190716,27335.63,-23.53,225998674.0,27398.68,27290.24,27349.32,-0.09,DJI@DJI,21535.25,-150.65,...,0.23,HSI@HSI,12430.97,43.63,75136056.0,12465.19,12366.97,12392.19,0.35,XTR@DAX30
20190715,27359.16,27.13,199725008.0,27364.69,27294.17,27364.69,0.10,DJI@DJI,NaN,NaN,...,0.29,HSI@HSI,12387.34,64.02,70764097.0,12434.14,12301.08,12346.59,0.52,XTR@DAX30
20190712,27332.03,243.95,248386381.0,27333.79,27135.45,27139.49,0.90,DJI@DJI,21685.90,42.37,...,0.14,HSI@HSI,12323.32,-8.80,78381758.0,12354.87,12304.98,12318.50,-0.07,XTR@DAX30
20190711,27088.08,227.88,252304479.0,27088.45,26916.32,26950.16,0.85,DJI@DJI,21643.53,110.05,...,0.81,HSI@HSI,12332.12,-41.29,78192163.0,12417.93,12307.34,12401.02,-0.33,XTR@DAX30
20190710,26860.20,76.71,207989938.0,26983.45,26813.11,26851.96,0.29,DJI@DJI,21533.48,-31.67,...,0.31,HSI@HSI,12373.41,-63.14,80443426.0,12448.81,12356.80,12412.99,-0.51,XTR@DAX30
20190709,26783.49,-22.65,218330307.0,26807.70,26665.57,26725.12,-0.08,DJI@DJI,21565.15,30.80,...,-0.76,HSI@HSI,12436.55,-106.96,105796865.0,12477.58,12364.16,12436.97,-0.85,XTR@DAX30
20190708,26806.14,-115.98,214290073.0,26839.14,26744.87,26835.64,-0.43,DJI@DJI,21534.35,-212.03,...,-1.54,HSI@HSI,12543.51,-25.02,91084363.0,12587.44,12507.72,12541.18,-0.20,XTR@DAX30
20190705,26922.12,-43.88,192171316.0,26950.81,26733.33,26867.75,-0.16,DJI@DJI,21746.38,43.93,...,-0.07,HSI@HSI,12568.53,-61.37,79900186.0,12632.12,12522.11,12632.12,-0.49,XTR@DAX30
20190703,26966.00,179.32,149841005.0,26966.00,26831.44,26832.32,0.67,DJI@DJI,21638.16,-116.11,...,-0.07,HSI@HSI,12616.24,89.52,70392698.0,12631.81,12545.79,12548.30,0.71,XTR@DAX30
20190702,26786.68,69.25,219268965.0,26787.56,26632.65,26719.53,0.26,DJI@DJI,21754.27,24.30,...,1.17,HSI@HSI,12526.72,5.34,68934477.0,12548.22,12484.26,12546.93,0.04,XTR@DAX30
20190701,26717.43,117.47,285350219.0,26890.64,26616.21,26805.86,0.44,DJI@DJI,21729.97,454.05,...,NaN,NaN,12521.38,122.58,93739950.0,12619.68,12519.30,12616.34,0.99,XTR@DAX30
20190628,26599.96,73.38,499348325.0,26638.35,26522.27,26605.93,0.28,DJI@DJI,21275.92,-62.25,...,-0.28,HSI@HSI,12398.80,127.77,99449250.0,12408.22,12297.63,12302.77,1.04,XTR@DAX30
20190627,26526.58,-10.24,246929846.0,26607.24,26465.32,26523.72,-0.04,DJI@DJI,21338.17,251.58,...,1.42,HSI@HSI,12271.03,25.71,85035616.0,12334.57,12209.34,12308.26,0.21,XTR@DAX30
20190626,26536.82,-11.40,274338528.0,26660.04,26536.33,26599.42,-0.04,DJI@DJI,21086.59,-107.22,...,0.13,HSI@HSI,12245.32,16.88,87524744.0,12315.84,12189.49,12210.52,0.14,XTR@DAX30
20190625,26548.22,-179.32,282163200.0,26752.31,26527.66,26731.61,-0.67,DJI@DJI,21193.81,-92.18,...,-1.15,HSI@HSI,12228.44,-46.13,73907229.0,12284.57,12213.41,12226.88,-0.38,XTR@DAX30
20190624,26727.54,8.41,232389229.0,26806.52,26723.37,26727.61,0.03,DJI@DJI,21285.99,27.35,...,0.14,HSI@HSI,12274.57,-65.35,89756318.0,12341.56,12250.71,12308.11,-0.53,XTR@DAX30
20190621,26719.13,-34.04,485562238.0,26907.37,26705.87,26749.12,-0.13,DJI@DJI,21258.64,-204.22,...,-0.27,HSI@HSI,12339.92,-15.47,210689661.0,12425.20,12316.41,12351.98,-0.13,XTR@DAX30
20190620,26753.17,249.17,278165159.0,26798.63,26539.69,26665.38,0.94,DJI@DJI,21462.86,128.99,...,1.23,HSI@HSI,12355.39,46.86,95166035.0,12438.37,12355.39,12409.58,0.38,XTR@DAX30
20190619,26504.00,38.46,240947088.0,26569.75,26415.05,26490.16,0.15,DJI@DJI,21333.87,361.16,...,2.56,HSI@HSI,12308.53,-23.22,104190582.0,12346.70,12291.19,12321.43,-0.19,XTR@DAX30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20040906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11244.37,221.88,...,1.20,HSI@HSI,3887.58,20.59,0.0,3891.62,3867.45,3867.45,0.53,XTR@DAX30
20040705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11541.71,-179.78,...,0.26,HSI@HSI,3995.73,-3.04,0.0,4011.54,3991.16,3998.19,-0.07,XTR@DAX30
20040611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11526.82,-49.15,...,-0.21,HSI@HSI,4014.56,-7.08,0.0,4019.38,3993.27,4017.45,-0.17,XTR@DAX30
20040531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11236.37,-73.20,...,0.67,HSI@HSI,3921.41,18.69,0.0,3927.95,3898.40,3904.39,0.47,XTR@DAX30
20040409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11897.51,-195.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20040216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10548.72,-8.97,...,0.66,HSI@HSI,4070.46,13.41,0.0,4070.46,4040.49,4054.96,0.33,XTR@DAX30
20040119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11036.33,179.13,...,0.64,HSI@HSI,4139.92,28.28,0.0,4151.72,4111.89,4111.89,0.68,XTR@DAX30
20031225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10365.35,-5.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20031127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10163.38,18.55,...,-0.08,HSI@HSI,3744.99,32.01,0.0,3756.11,3729.18,3741.63,0.86,XTR@DAX30
20030901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10670.18,326.63,...,-0.05,HSI@HSI,3571.22,86.64,0.0,3577.87,3493.34,3493.34,2.48,XTR@DAX30
20030704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9547.73,-77.07,...,-0.09,HSI@HSI,3239.61,-2.31,0.0,3243.73,3213.61,3237.80,-0.07,XTR@DAX30
20030526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8227.32,42.56,...,2.03,HSI@HSI,2828.28,5.45,0.0,2855.28,2812.40,2821.54,0.19,XTR@DAX30
20030418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7874.51,52.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20030217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8771.89,69.97,...,1.97,HSI@HSI,2708.97,34.51,0.0,2722.30,2679.95,2683.48,1.29,XTR@DAX30
20030120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8558.82,-131.43,...,-0.65,HSI@HSI,2893.55,-25.27,0.0,2966.78,2892.93,2927.58,-0.86,XTR@DAX30
20021225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8501.14,-11.23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20021128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9176.78,300.90,...,2.04,HSI@HSI,3360.76,14.62,0.0,3376.99,3305.44,3342.58,0.43,XTR@DAX30
20020902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9521.63,-97.67,...,-1.46,HSI@HSI,3609.41,-103.53,0.0,3698.69,3602.37,3698.69,-2.78,XTR@DAX30
20020704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10632.81,-179.49,...,1.76,HSI@HSI,4258.62,120.47,0.0,4258.62,4140.43,4140.43,2.91,XTR@DAX30
20020527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11976.35,0.07,...,-0.53,HSI@HSI,4961.54,62.41,0.0,4972.21,4896.84,4896.84,1.27,XTR@DAX30
20020329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11024.94,-308.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20020218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10093.25,45.15,...,0.37,HSI@HSI,4871.76,9.16,0.0,4894.49,4840.88,4865.83,0.18,XTR@DAX30
20020121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10280.25,-13.07,...,0.24,HSI@HSI,5069.74,-52.49,0.0,5122.40,5021.21,5122.40,-1.02,XTR@DAX30
20171123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.99,HSI@HSI,13008.55,-6.49,71297569.0,13049.08,12921.15,12943.49,-0.05,XTR@DAX30
20070102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.73,HSI@HSI,6681.13,84.21,0.0,6682.81,6614.73,6614.73,1.28,XTR@DAX30
20061123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.08,HSI@HSI,6475.25,-0.88,0.0,6494.70,6461.58,6483.58,-0.01,XTR@DAX30
20170102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11598.33,117.27,48923819.0,11617.28,11414.82,11426.38,1.02,XTR@DAX30
20120102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6075.52,177.17,0.0,6075.52,5900.18,5900.18,3.00,XTR@DAX30
20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5449.98,41.72,0.0,5451.57,5409.28,5410.24,0.77,XTR@DAX30
20090329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
jisu_exp_info_df.shape

(4575, 72)

In [40]:
jisu_exp_info_df.isnull().sum()

종가_DJI@DJI          148
전일비_DJI@DJI         148
gvol_DJI@DJI        148
고가_DJI@DJI          148
저가_DJI@DJI          148
시가_DJI@DJI          148
rate_DJI@DJI        148
symb_DJI@DJI        148
종가_NII@NI225        263
전일비_NII@NI225       263
gvol_NII@NI225      263
고가_NII@NI225        263
저가_NII@NI225        263
시가_NII@NI225        263
rate_NII@NI225      263
symb_NII@NI225      263
종가_LNS@FTSE100      142
전일비_LNS@FTSE100     142
gvol_LNS@FTSE100    142
고가_LNS@FTSE100      142
저가_LNS@FTSE100      142
시가_LNS@FTSE100      142
rate_LNS@FTSE100    142
symb_LNS@FTSE100    142
종가_NAS@IXIC         150
전일비_NAS@IXIC        150
gvol_NAS@IXIC       150
고가_NAS@IXIC         150
저가_NAS@IXIC         150
시가_NAS@IXIC         150
                   ...
gvol_PAS@CAC40       82
고가_PAS@CAC40         82
저가_PAS@CAC40         82
시가_PAS@CAC40         82
rate_PAS@CAC40       82
symb_PAS@CAC40       82
종가_SPI@SPX          147
전일비_SPI@SPX         147
gvol_SPI@SPX        147
고가_SPI@SPX          147
저가_SPI@SPX          147
시가_SPI@SPX          147
rate_SPI@SPX        147
symb_SPI@SPX        147
종가_HSI@HSI          241
전일비_HSI@HSI         241
gvol_HSI@HSI        241
고가_HSI@HSI          241
저가_HSI@HSI          241
시가_HSI@HSI          241
rate_HSI@HSI        241
symb_HSI@HSI        241
종가_XTR@DAX30        121
전일비_XTR@DAX30       121
gvol_XTR@DAX30      121
고가_XTR@DAX30        121
저가_XTR@DAX30        121
시가_XTR@DAX30        121
rate_XTR@DAX30      121
symb_XTR@DAX30      121
Length: 72, dtype: int64

- 환율

In [41]:
base_url_exchange = 'https://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_'

In [42]:
code_exchange = ['USDKRW', 'JPYKRW', 'EURKRW', 'CNYKRW']

In [72]:
exchange_info_df = pd.DataFrame()
for i in code_exchange :
    temp = info_collector_html(base_url_exchange, i)
    temp = temp[['날짜', '매매기준율', '전일대비']]
    temp = temp.drop_duplicates(['날짜'])
    temp.set_index('날짜', inplace=True)
    temp.columns = (temp.columns + '_' + i)
    exchange_info_df = pd.concat([exchange_info_df, temp], axis=1, sort=False)
exchange_info_df

,매매기준율_USDKRW,전일대비_USDKRW,매매기준율_JPYKRW,전일대비_JPYKRW,매매기준율_EURKRW,전일대비_EURKRW,매매기준율_CNYKRW,전일대비_CNYKRW
날짜,매매기준율,전일대비,매매기준율,전일대비,매매기준율,전일대비,매매기준율,전일대비
2019.08.01,1187.90,4.90,1087.69,1.93,1312.14,6.43,NaN,NaN
2019.07.31,1183.00,2.00,1089.62,2.09,1318.57,2.11,NaN,NaN
2019.07.30,1181.00,3.50,1087.53,2.72,1316.46,1.06,NaN,NaN
2019.07.29,1184.50,0.00,1090.25,0.20,1317.52,1.07,NaN,NaN
2019.07.26,1184.50,3.00,1090.05,3.27,1318.59,1.87,NaN,NaN
2019.07.25,1181.50,3.00,1093.32,2.57,1316.72,2.22,NaN,NaN
2019.07.24,1178.50,0.50,1090.75,0.24,1314.50,3.80,NaN,NaN
2019.07.23,1179.00,1.50,1090.51,1.03,1318.30,3.09,NaN,NaN
2019.07.22,1177.50,2.00,1091.54,0.88,1321.39,0.42,NaN,NaN
2019.07.19,1175.50,3.00,1092.42,0.05,1320.97,0.48,NaN,NaN
2019.07.18,1178.50,2.50,1092.47,1.63,1321.45,3.40,NaN,NaN
2019.07.17,1181.00,2.50,1090.84,1.07,1324.85,1.28,NaN,NaN
2019.07.16,1178.50,1.50,1091.91,1.59,1323.57,7.29,NaN,NaN
2019.07.15,1180.00,1.00,1093.50,5.21,1330.86,3.31,NaN,NaN
2019.07.12,1179.00,5.00,1088.29,2.81,1327.55,4.57,NaN,NaN
2019.07.11,1174.00,7.50,1085.48,0.79,1322.98,2.49,NaN,NaN
2019.07.10,1181.50,1.50,1084.69,2.78,1325.47,0.02,NaN,NaN
2019.07.09,1183.00,2.50,1087.47,0.20,1325.49,1.74,NaN,NaN
2019.07.08,1180.50,9.00,1087.67,3.60,1323.75,4.41,NaN,NaN
2019.07.05,1171.50,2.50,1084.07,0.50,1319.34,0.18,NaN,NaN
2019.07.04,1169.00,1.50,1084.57,2.70,1319.16,3.27,NaN,NaN
2019.07.03,1170.50,3.00,1087.27,8.70,1322.43,3.27,NaN,NaN
2019.07.02,1167.50,4.50,1078.57,4.35,1319.16,1.36,NaN,NaN
2019.07.01,1163.00,7.50,1074.22,1.08,1317.80,2.55,NaN,NaN
2019.06.28,1155.50,1.00,1073.14,0.67,1315.25,0.90,NaN,NaN
2019.06.27,1156.50,0.00,1072.47,1.60,1316.15,1.73,NaN,NaN
2019.06.26,1156.50,0.50,1074.07,6.86,1314.42,1.80,NaN,NaN
2019.06.25,1156.00,1.50,1080.93,2.43,1316.22,2.29,NaN,NaN
2019.06.24,1157.50,6.00,1078.50,3.27,1318.51,2.94,NaN,NaN
...,...,...,...,...,...,...,...,...
2004.05.25,1177.70,0.50,1045.26,0.72,1419.72,13.91,NaN,NaN
2004.05.24,1177.20,1.90,1044.54,5.49,1405.81,6.08,NaN,NaN
2004.05.21,1175.30,4.50,1050.03,11.11,1411.89,5.21,NaN,NaN
2004.05.20,1179.80,6.40,1038.92,2.71,1406.68,2.93,NaN,NaN
2004.05.19,1173.40,8.60,1036.21,2.55,1409.61,7.14,NaN,NaN
2004.05.18,1182.00,1.50,1038.76,2.23,1416.75,1.08,NaN,NaN
2004.05.17,1183.50,3.50,1040.99,4.22,1417.83,18.12,NaN,NaN
2004.05.14,1187.00,1.50,1036.77,2.41,1399.71,6.53,NaN,NaN
2004.05.13,1185.50,4.00,1039.18,7.78,1406.24,4.98,NaN,NaN
2004.05.12,1181.50,6.80,1046.96,1.39,1401.26,10.08,NaN,NaN
2004.05.11,1188.30,5.20,1048.35,0.34,1411.34,10.90,NaN,NaN
2004.05.10,1183.10,12.00,1048.01,12.29,1400.44,10.74,NaN,NaN
2004.05.07,1171.10,5.00,1060.30,7.46,1411.18,7.85,NaN,NaN
2004.05.06,1166.10,3.70,1067.76,8.64,1419.03,20.77,NaN,NaN
2004.05.04,1169.80,2.00,1059.12,4.99,1398.26,5.79,NaN,NaN
2004.05.03,1171.80,1.50,1064.11,0.76,1404.05,1.49,NaN,NaN
2004.04.30,1173.30,2.60,1063.35,2.26,1402.56,18.79,NaN,NaN
2004.04.29,1170.70,14.30,1061.09,2.79,1383.77,9.04,NaN,NaN
2004.04.28,1156.40,4.40,1058.30,3.65,1374.73,4.77,NaN,NaN
2004.04.27,1152.00,3.00,1061.95,3.68,1369.96,6.37,NaN,NaN
2004.04.26,1155.00,3.30,1058.27,0.31,1363.59,16.41,NaN,NaN
2004.04.23,1158.30,1.40,1058.58,0.60,1380.00,10.51,NaN,NaN
2004.04.22,1159.70,4.90,1059.18,3.00,1369.49,0.94,NaN,NaN
2004.04.21,1154.80,3.40,1062.18,2.85,1368.55,5.53,NaN,NaN
2004.04.20,1151.40,2.20,1065.03,4.60,1374.08,17.39,NaN,NaN
2004.04.19,1153.60,6.50,1069.63,0.57,1391.47,0.53,NaN,NaN
2004.04.16,1160.10,8.80,1070.20,2.67,1392.00,16.77,NaN,NaN
2004.04.14,1151.30,10.20,1072.87,9.25,1375.23,5.00,139.10,1.24
2004.04.13,1141.10,0.70,1082.12,7.99,1370.23,8.15,137.86,0.09
2004.04.12,1141.80,1141.80,1074.13,1074.13,1378.38,1378.38,137.95,137.95

In [73]:
exchange_info_df.shape

(3807, 8)

In [74]:
exchange_info_df.isna().sum()

매매기준율_USDKRW       0
전일대비_USDKRW        0
매매기준율_JPYKRW       0
전일대비_JPYKRW        0
매매기준율_EURKRW       0
전일대비_EURKRW        0
매매기준율_CNYKRW    3803
전일대비_CNYKRW     3803
dtype: int64

-

In [ ]:
https://finance.naver.com/
    sise/
    sise_index_day.nhn?
    code=
    KOSPI
    &page=
    {i}

In [120]:
url_creater('국내금')

['https://finance.naver.com/marketindex/goldDailyQuote.nhn?&page=']

In [86]:
aa = {'a' : 'aa', 'b':['z','x','c'], 'c':[]}
aa

{'a': 'aa', 'b': ['z', 'x', 'c'], 'c': []}

In [91]:
len(aa['b'])

3

In [79]:
type(aa['b'])

list

In [88]:
aa['c']

[]

In [ ]:
https://finance.naver.com/
    marketindex/
    worldDailyQuote.nhn?
    marketindex
    Cd=OIL_CL
    &fdtc=2&page=1

In [ ]:
https://finance.naver.com/
    marketindex/
    oilDailyQuote.nhn?
    marketindex
    Cd=OIL_GSL
    &page=1

In [ ]:
https://finance.naver.com/
    marketindex/
    worldDailyQuote.nhn?
    marketindexCd=CMDT_GC
    &fdtc=2&page=1

In [ ]:
https://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_USDKRW&page=1

In [ ]:
https://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_JPYKRW&page=1

In [ ]:
https://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=OIL_CL&fdtc=2&page=1

## ---------------------------------------------------------------------

In [ ]:
aa = info_collector_ajax(base_url_jisu_exp, 'DJI@DJI')
aa

In [ ]:
type(aa)

In [ ]:
target_url = base_url_jisu_exp + code_jisu_exp[0]
target_url

In [ ]:
iii = 1
page_url = (f'{target_url}&fdtc=0&page={iii}')
page_url

In [ ]:
requests.get(page_url).text

In [ ]:
requests.get(page_url).json()

In [ ]:
pd.DataFrame(requests.get(page_url).json())

In [ ]:
info_df = pd.DataFrame()

In [ ]:
info_df.append(pd.DataFrame(requests.get(page_url).json()))

In [ ]:
https://finance.naver.com/world/worldDayListJson.nhn?symbol=DJI@DJI&fdtc=0&page=2

In [ ]:
https://finance.naver.com/world/worldDayListJson.nhn?symbol=NII@NI225&fdtc=0&page=1

In [ ]:
https://finance.naver.com/world/worldDayListJson.nhn?symbol=LNS@FTSE100&fdtc=0&page=2

In [ ]:
info_collector_html(base_url_jisu_do, 'KOSPI')

#### jisu information

In [ ]:
## KOSPI, KOSDAQ, KOSPI200

In [ ]:
## 다우산업, 니케이225, 영국, 나스닥종합, 상해종합, 프랑스, S&P 500, 항셍, 독일

In [ ]:
https://finance.naver.com/sise/sise_index.nhn?code=KOSPI
https://finance.naver.com/sise/sise_index.nhn?code=KOSDAQ
https://finance.naver.com/sise/sise_index.nhn?code=KPI200

In [ ]:
import requests
import json

In [ ]:
uuu = 'https://finance.naver.com/world/worldDayListJson.nhn?symbol=DJI@DJI&fdtc=0&page=1'

In [ ]:
aaa = json.loads(requests.get(uuu).text)
aaa

In [ ]:
pd.DataFrame(aaa)

In [ ]:
basic_item = ['KOSPI']

In [ ]:
interest_item = ['삼성전자']

In [ ]:
input_item = basic_item + interest_item
input_item

In [ ]:
input_code = list(sto_code_sort[sto_code_sort['회사명'].isin(input_item)]['종목코드'].values)
input_code

005930

In [ ]:
sise_url = 'https://finance.naver.com/sise/sise_index_day.nhn?code=005930'
sise_url

In [ ]:
sise_html = BeautifulSoup(urlopen(sise_url).read(), 'lxml')
sise_html

In [ ]:
page_pkg = sise_html.find_all("table",align="center")
page_pkg

In [ ]:
last_page_num = last_page_finder(sise_html)

In [ ]:
sise_exporter('KOSPI')

In [ ]:
sise_exporter('005930')

In [ ]:
sise_df = pd.DataFrame()
for i in input_code :
    sise_url = 'https://finance.naver.com/sise/sise_index_day.nhn?code=' + i
    sise_html = BeautifulSoup(urlopen(sise_url).read(), 'lxml') #html.parser
    last_page_num = last_page_finder(sise_html)
    for j in range(1, last_page+1) :
        url = (f'{sise_url}&page={i}')
        sise_df = sise_df.append(pd.read_html(url, header=0)[0], ignore_index=True)

In [ ]:
sise_url = 'https://finance.naver.com/sise/sise_index_day.nhn?code=' + item_code

In [ ]:
source_html = BeautifulSoup(urlopen(sise_url).read(), 'lxml') #html.parser

In [ ]:
last_page = last_page_finder(source_html)

In [ ]:
sise_df = pd.DataFrame()

In [ ]:
for i in range(1, last_page+1):
    url = (f'{sise_url}&page={i}')
    sise_df = sise_df.append(pd.read_html(url, header=0)[0], ignore_index=True)

sise_df

In [ ]:
sise_df = sise_df.dropna(axis=0)
sise_df[-5:]

In [ ]:
type(sise_df['체결가'].values[0])

In [ ]:
sise_df['날짜'] = pd.to_datetime(sise_df['날짜'])

In [ ]:
sise_df['등락률'] = sise_df['등락률'].map(lambda x: float(x.split("%")[0].strip()))

In [ ]:
sise_df.dtypes

In [ ]:
sise_df[-5:]

In [ ]:
sise_save = 'data/sise_list/' + item_code + '_' + date_key + '.csv'
sise_save

In [ ]:
sise_df.to_csv(sise_save, encoding='euc-kr', index=False) #cp949
print('save >> ' + sise_save)

In [43]:
aaa = pd.DataFrame( {
            'first_name': ['Jason', 'Jason', 'Tina', 'Jake', 'Amy'],
            'last_name': ['Miller', 'Miller', 'Ali', 'Milner', 'Cooze'],
            'age': [42, 42, 36, 24, 73],
            'preTestScore': [42, 42, 31, 2, 42],
            'postTestScore': [25, 25, 57, 62, 70]})
aaa

  first_name last_name  age  preTestScore  postTestScore
0      Jason    Miller   42            42             25
1      Jason    Miller   42            42             25
2       Tina       Ali   36            31             57
3       Jake    Milner   24             2             62
4        Amy     Cooze   73            42             70

In [45]:
aaa[['first_name','age' ]]

  first_name  age
0      Jason   42
1      Jason   42
2       Tina   36
3       Jake   24
4        Amy   73

In [ ]:
a1 = pd.DataFrame( {
            'first_name': ['Jason', 'Bason', 'Tina', 'Jake'],
            'last_name': ['Miller', 'Miller', 'Ali', 'Milner'],
            'age': [42, 42, 36, 24] })
a1.set_index('first_name', inplace=True)
a1

In [ ]:
a2 = pd.DataFrame( {
            'first_name': ['Bason','Jake', 'Jason', 'Tina', 'Amy'],
            'last_name': ['Miller', 'Miller', 'Ali', 'Milner', 'Cooze'],
            'age': [42, 42, 36, 24, 99] })
a2.set_index('first_name', inplace=True)
a2

In [ ]:
pd.concat([a1, a2], axis=1)

In [ ]:
pd.concat([a1, a2], axis=1, sort=False)